# Generated by Django 5.2.7 on 2025-11-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cases', '0002_casecomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='process_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
