# Generated by Django 5.2.7 on 2025-11-05 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_cases', '0004_add_responsibles_and_actuaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='caseresponsible',
            constraint=models.UniqueConstraint(condition=models.Q(('left_at__isnull', True), ('role', 'principal')), fields=('case',), name='unique_principal_per_case'),
        ),
    ]
