from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(max_length=255, null=True, blank=True)),
                ('action', models.CharField(max_length=255)),
                ('object_type', models.CharField(max_length=128, null=True, blank=True)),
                ('object_id', models.CharField(max_length=128, null=True, blank=True)),
                ('details', models.JSONField(null=True, blank=True)),
            ],
            options={'ordering': ['-timestamp']},
        ),
    ]
# Generated by Django 5.2.7 on 2025-11-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('action', models.CharField(max_length=255)),
                ('object_type', models.CharField(blank=True, max_length=128, null=True)),
                ('object_id', models.CharField(blank=True, max_length=128, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
