# Generated by Django 5.2.7 on 2025-11-06 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='mobile',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='nit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
